import React from "react";
import "./index.css";

export default function Details() {
  return (
    <div className="Description">
      <h5 className="details">Details</h5>
      <p className="text1">
        IThe PROGNOS® for Aircraft operational solution is based on the
        collection and analysis of technical data generated by the thousands of
        sensors installed on the aircraft's systems. This continuous stream of
        flight data is extrated and analyzed by the application and transmitted
        to our maintenance control centers, where our specialists regularly
        receive alerts about defective components. This exercise is made
        possible by the very great amount of data – up to Gb – supplied by
        new-generation aircraft and our extensive engineering knowledge.
        <br />
        <br />
        Using our in-depth engineering knowledge and Big Data from the aircraft,
        algorithms are developed that have a very high accuracy. All the
        replacements initiated by the Prognos solutions were confirmed faulty by
        the repair shop. The algorithms are continuously improved based on the
        data provided by the aircraft (such as electrical power, speed, angle of
        attack, or temperature) but also on the shop feedback, which allow
        continious improvment based on new failure cases.
      </p>
    </div>
  );
}
